### ISSUE TITLE
Some way to run "cleanup" actions

### ISSUE THREAD

**Issue by paulbellamy** [actions/workflow-parser#32]
For workflows which create resources, or leave things in a "dirty" state, it would be nice to have a way to specify a cleanup or teardown action.

Maybe something like:
```hcl
workflow "my workflow" {
  on = "push"
  resolves = ["create some resources and do some work"]
  after = ["delete the resources"] # new cleanup action which always runs
}
```
or, you could include the cleanup action in the normal workflow, so with only a new failure resolver:
```hcl
workflow "my workflow" {
  on = "push"
  resolves = ["use and delete some resources normally"]
  failure = ["handle the error"] # only runs when the workflow fails
}
```

wdyt?

**Comment by piki** [comment]
@paulbellamy We're tracking requests for failure (aka `rescue` or `catch` or `failure`) handlers and unconditional cleanup (`ensure` or `finally` or `after`) handlers as part of the broader Actions platform.  I've cross-linked your issue to that (internal) issue.

I'm going to close this issue here, because the parser can't do anything useful here without buy-in from the rest of the project.  This is a known issue, and I've added your suggestions to the mix.

**Comment by paulbellamy** [comment]
Thanks, I wasn't sure where to put the issue.

**Comment by piki** [comment]
This [contact form](https://github.com/contact?form%5Bsubject%5D=Re:%20GitHub%20Actions) linked from the [Actions developer docs](https://developer.github.com/actions/) is the official channel, but your issue here got routed to the right place, too.
