### ISSUE TITLE
Parser should report an error on resolves=workflow

### ISSUE THREAD

**Issue by OmarTawfik** [actions/workflow-parser#46]
The following test is missing one more diagnostic:

https://github.com/actions/workflow-parser/blob/5eccc7e7dc298710bb757d0f7b5a72f5df9f5425/tests/invalid/workflow-keywords-redefined.workflow#L9-L12

Accourding to [the spec](https://github.com/actions/workflow-parser/blob/master/language.md):

> "resolves" identifies one or more actions that will be resolved when the given event occurs.

`resolves=["b"]` should be an error because `b` is a workflow, not an action. So I was expecting another error in the form:

`{ "line": 11, "severity": "ERROR", "message": "workflow 'b' resolves unknown action 'b'" }`

This was found during working on https://github.com/OmarTawfik/github-actions-js/issues/79
cc @piki

**Comment by piki** [comment]
Line 11 doesn't raise an error, because line 12 overrides it.  By the time we get to the `checkFlows` function that looks for dangling `resolves`, only the `resolves=["c"]` from line 12 is remembered.  The parser in effect makes three passes:
 1. syntax, converting text to an HCL AST
 2. type checking, converting that AST to `Action` and `Workflow` data structures
 3. linking, ensuring that data structures are complete and link to each other in valid ways

Pass (2) sees that line 12 redefines line 11 and remembers only line 12.  Pass (3) checks that all the `resolves` are valid, so it complains about line 12.

If you remove line 12, line 11 generates the `unknown action b` error you'd expect.

**Comment by OmarTawfik** [comment]
@piki I understand why it is not being reported, but I filed it as I remember you talking about wanting to match diagnostics across different tools. My plan was to keep filing these differences in case someone wants to improve error reporting for later. 

If you don't think these are actionable, I'll just override it in my project and stop creating issues here to reduce noise 😄

**Comment by piki** [comment]
@OmarTawfik I'm happy to fix some of the discrepancies.  This one is pretty deep, because fixing it requires changing how the three parser passes talk to each other.  For example, emitting an `unknown action b` error in pass 2 requires resolving forward references, presumably by adding another pass beforehand to set up a map of top-level blocks.  Emitting it in pass 3 requires having pass 2 persist overwritten values, i.e., adding fields to the data structure that are only used for broken workflow files.

I'd do one or the other if I thought it made a difference to end-user usability, but not for a unit test.  So I'm going to close this.

I welcome issues for other discrepancies here, though, especially if they'll make it easier for an end user to debug their workflow files.
